### ISSUE TITLE
Readme is missing necessary information

### ISSUE THREAD

**Issue by ohcibi** [browserstack/browserstack-testem-integration#4]
The instructions in the README.md which were changed here: https://github.com/browserstack/browserstack-testem-integration/commit/a21bd8a2134ae3354d1cacfa3a052d5f7f7e3955 do not work. There are several issues:

1. Why is there a hello-world script in this repository?
2. There is `start-...Local` and a `stop-...Local` script. What are they for? How and when should one run them?
3. Is this repository actually needed except for its information in the README.md? The instructions do not make any use of any file in this repository
4. Why are the information about browserstack-cli removed? As far as I can see it is still necessary to get this to work

**Comment by vedharish** [comment]
What specific issues did you have with the changes? It works fine for me. Can you please mention what steps you were following, which node version are you using and what doesn't work.

To be clear this repo has example code to run [jasmine](https://github.com/jasmine/jasmine) tests on [Browserstack](https://browserstack.com/) infrastructure using [testem](https://github.com/testem/testem) javascript framework.

Regarding your questions -

1. the hello-world script (hello.js and hello_spec.js) together forms a [jasmine test suite](https://jasmine.github.io/edge/introduction.html). hello_spec.js is the spec file that describes the test and hello.js is the function that the spec file uses. Basically, we are running a test which runs the javascript function 'hello' in hello.js.

2. BrowserStack has a [feature](https://www.browserstack.com/local-testing) which allows to test private servers or hosted files. What these scripts basically do is to start a binary which enables this feature, before starting the tests, and after the tests are finished, stops the binary. Hence the name. Testem has nice [on-start](https://github.com/browserstack/browserstack-testem-integration/blob/7fa5a889afc866c7e63603ef1a12db5e5a2f2f4e/testem.json#L5) and [on-exit](https://github.com/browserstack/browserstack-testem-integration/blob/7fa5a889afc866c7e63603ef1a12db5e5a2f2f4e/testem.json#L9) hooks to allow executing scripts before and after tests. Testem itself calls these scripts, when `testem ci` is run (fifth and sixth lines in README)

3. `testem ci` uses the [testem configuration file](https://github.com/testem/testem/blob/master/docs/config_file.md) which in turn uses the other files in the repo

4. This repo no longer uses the old [browserstack-cli](https://github.com/airportyh/browserstack-cli/) utility as it had some issues with not being up-to-date with BrowserStack features.

I will close this issue. You are welcome to reopen and comment if you need more info or if you think something is amiss with this repo and needs to be included or have problems with its workings. Or to better understand how things work you can drop a mail to support@browserstack.com. The guys there are awesome!

**Comment by ohcibi** [comment]
@vedharish I found out that one actually has to use this whole repository (especially the things in testem.json) 8-). I'd say the repository-name is missing an `-example` suffix. Anyways, I made an npm-package from this and called it `browserstack-testem-integration` and put information about the needed parts in a project's `testem.json` in its readme. All fine now

**Comment by vedharish** [comment]
Nice! :+1:
